// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterWorkerRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub capabilities: ::core::option::Option<WorkerCapabilities>,
    #[prost(map = "string, string", tag = "3")]
    pub platform_properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Empty for now, could return configuration
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisterWorkerResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WorkerCapabilities {
    #[prost(int32, tag = "1")]
    pub max_concurrent_executions: i32,
    #[prost(message, optional, tag = "2")]
    pub resources: ::core::option::Option<ResourceLimits>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResourceLimits {
    #[prost(double, tag = "1")]
    pub cpu_cores: f64,
    #[prost(int64, tag = "2")]
    pub memory_bytes: i64,
    #[prost(int64, tag = "3")]
    pub disk_bytes: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaseTaskRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub max_tasks: i32,
    #[prost(int64, tag = "3")]
    pub timeout_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaseTaskResponse {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<LeasedTask>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeasedTask {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub operation_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub action_digest: ::core::option::Option<
        super::super::super::build::bazel::remote::execution::v2::Digest,
    >,
    #[prost(message, optional, tag = "4")]
    pub timeout: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "5")]
    pub lease_expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTaskStatusRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "3")]
    pub status: i32,
    #[prost(message, optional, tag = "4")]
    pub result: ::core::option::Option<
        super::super::super::build::bazel::remote::execution::v2::ActionResult,
    >,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
}
/// Empty
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateTaskStatusResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkerState", tag = "2")]
    pub state: i32,
    #[prost(message, optional, tag = "3")]
    pub stats: ::core::option::Option<WorkerStats>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WorkerStats {
    #[prost(int32, tag = "1")]
    pub active_tasks: i32,
    #[prost(int64, tag = "2")]
    pub total_completed: i64,
    #[prost(int64, tag = "3")]
    pub total_failed: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatResponse {
    #[prost(bool, tag = "1")]
    pub should_shutdown: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterWorkerRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
/// Empty
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnregisterWorkerResponse {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskStatus {
    Unknown = 0,
    Executing = 1,
    Completed = 2,
    Failed = 3,
}
impl TaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "TASK_STATUS_UNKNOWN",
            Self::Executing => "TASK_STATUS_EXECUTING",
            Self::Completed => "TASK_STATUS_COMPLETED",
            Self::Failed => "TASK_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TASK_STATUS_UNKNOWN" => Some(Self::Unknown),
            "TASK_STATUS_EXECUTING" => Some(Self::Executing),
            "TASK_STATUS_COMPLETED" => Some(Self::Completed),
            "TASK_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkerState {
    Unknown = 0,
    Idle = 1,
    Busy = 2,
    Draining = 3,
}
impl WorkerState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "WORKER_STATE_UNKNOWN",
            Self::Idle => "WORKER_STATE_IDLE",
            Self::Busy => "WORKER_STATE_BUSY",
            Self::Draining => "WORKER_STATE_DRAINING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORKER_STATE_UNKNOWN" => Some(Self::Unknown),
            "WORKER_STATE_IDLE" => Some(Self::Idle),
            "WORKER_STATE_BUSY" => Some(Self::Busy),
            "WORKER_STATE_DRAINING" => Some(Self::Draining),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod worker_scheduler_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct WorkerSchedulerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WorkerSchedulerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WorkerSchedulerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WorkerSchedulerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WorkerSchedulerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn register_worker(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterWorkerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/expbuild.worker.v1.WorkerScheduler/RegisterWorker",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "expbuild.worker.v1.WorkerScheduler",
                        "RegisterWorker",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn lease_task(
            &mut self,
            request: impl tonic::IntoRequest<super::LeaseTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaseTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/expbuild.worker.v1.WorkerScheduler/LeaseTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("expbuild.worker.v1.WorkerScheduler", "LeaseTask"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_task_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateTaskStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateTaskStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/expbuild.worker.v1.WorkerScheduler/UpdateTaskStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "expbuild.worker.v1.WorkerScheduler",
                        "UpdateTaskStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn report_heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/expbuild.worker.v1.WorkerScheduler/ReportHeartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "expbuild.worker.v1.WorkerScheduler",
                        "ReportHeartbeat",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn unregister_worker(
            &mut self,
            request: impl tonic::IntoRequest<super::UnregisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterWorkerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/expbuild.worker.v1.WorkerScheduler/UnregisterWorker",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "expbuild.worker.v1.WorkerScheduler",
                        "UnregisterWorker",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod worker_scheduler_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with WorkerSchedulerServer.
    #[async_trait]
    pub trait WorkerScheduler: std::marker::Send + std::marker::Sync + 'static {
        async fn register_worker(
            &self,
            request: tonic::Request<super::RegisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterWorkerResponse>,
            tonic::Status,
        >;
        async fn lease_task(
            &self,
            request: tonic::Request<super::LeaseTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaseTaskResponse>,
            tonic::Status,
        >;
        async fn update_task_status(
            &self,
            request: tonic::Request<super::UpdateTaskStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateTaskStatusResponse>,
            tonic::Status,
        >;
        async fn report_heartbeat(
            &self,
            request: tonic::Request<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        >;
        async fn unregister_worker(
            &self,
            request: tonic::Request<super::UnregisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterWorkerResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct WorkerSchedulerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> WorkerSchedulerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for WorkerSchedulerServer<T>
    where
        T: WorkerScheduler,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/expbuild.worker.v1.WorkerScheduler/RegisterWorker" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterWorkerSvc<T: WorkerScheduler>(pub Arc<T>);
                    impl<
                        T: WorkerScheduler,
                    > tonic::server::UnaryService<super::RegisterWorkerRequest>
                    for RegisterWorkerSvc<T> {
                        type Response = super::RegisterWorkerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterWorkerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerScheduler>::register_worker(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterWorkerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/expbuild.worker.v1.WorkerScheduler/LeaseTask" => {
                    #[allow(non_camel_case_types)]
                    struct LeaseTaskSvc<T: WorkerScheduler>(pub Arc<T>);
                    impl<
                        T: WorkerScheduler,
                    > tonic::server::UnaryService<super::LeaseTaskRequest>
                    for LeaseTaskSvc<T> {
                        type Response = super::LeaseTaskResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LeaseTaskRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerScheduler>::lease_task(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LeaseTaskSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/expbuild.worker.v1.WorkerScheduler/UpdateTaskStatus" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateTaskStatusSvc<T: WorkerScheduler>(pub Arc<T>);
                    impl<
                        T: WorkerScheduler,
                    > tonic::server::UnaryService<super::UpdateTaskStatusRequest>
                    for UpdateTaskStatusSvc<T> {
                        type Response = super::UpdateTaskStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateTaskStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerScheduler>::update_task_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateTaskStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/expbuild.worker.v1.WorkerScheduler/ReportHeartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct ReportHeartbeatSvc<T: WorkerScheduler>(pub Arc<T>);
                    impl<
                        T: WorkerScheduler,
                    > tonic::server::UnaryService<super::HeartbeatRequest>
                    for ReportHeartbeatSvc<T> {
                        type Response = super::HeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerScheduler>::report_heartbeat(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReportHeartbeatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/expbuild.worker.v1.WorkerScheduler/UnregisterWorker" => {
                    #[allow(non_camel_case_types)]
                    struct UnregisterWorkerSvc<T: WorkerScheduler>(pub Arc<T>);
                    impl<
                        T: WorkerScheduler,
                    > tonic::server::UnaryService<super::UnregisterWorkerRequest>
                    for UnregisterWorkerSvc<T> {
                        type Response = super::UnregisterWorkerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnregisterWorkerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WorkerScheduler>::unregister_worker(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnregisterWorkerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for WorkerSchedulerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "expbuild.worker.v1.WorkerScheduler";
    impl<T> tonic::server::NamedService for WorkerSchedulerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
