import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createPool, migrate } from './db.js';
import { buildApp } from './app.js';
import { hashPassword } from './security.js';

test('PostgreSQL-backed sessions, project permissions and audit are isolated', { skip: !process.env.TEST_DATABASE_URL }, async () => {
  const base = process.env.TEST_DATABASE_URL!;
  const root = createPool(base), database = `expbuild_test_${randomUUID().replaceAll('-', '')}`;
  await root.query(`CREATE DATABASE "${database}"`);
  const url = new URL(base); url.pathname = `/${database}`;
  const pool = createPool(url.toString());
  const origin = 'http://localhost:5173';
  const app = await buildApp(pool, { origin, secureCookies: false });
  try {
    await migrate(pool); await migrate(pool);
    const password = 'test-password-with-enough-length', hashed = await hashPassword(password);
    const admin = randomUUID(), viewer = randomUUID(), stranger = randomUUID();
    for (const [id, email, elevated] of [[admin, 'admin@example.test', true], [viewer, 'viewer@example.test', false], [stranger, 'stranger@example.test', false]]) {
      await pool.query('INSERT INTO users(id,email,password_hash,platform_admin) VALUES($1,$2,$3,$4)', [id, email, hashed, elevated]);
    }
    const login = async (email: string) => {
      const response = await app.inject({ method: 'POST', url: '/v1/auth/login', headers: { origin }, payload: { email, password } });
      assert.equal(response.statusCode, 200, response.body);
      assert.ok(response.cookies[0]?.httpOnly);
      return { origin, cookie: `expbuild_session=${response.cookies[0]!.value}`, 'x-csrf-token': response.json().csrfToken as string };
    };
    const adminHeaders = await login('admin@example.test');
    const anonymousContract=await app.inject({url:'/v1/openapi.json'});assert.equal(anonymousContract.statusCode,401);
    const contract=await app.inject({url:'/v1/openapi.json',headers:adminHeaders});assert.equal(contract.statusCode,200,contract.body);assert.equal(contract.json().openapi,'3.1.0');
    const viewerHeaders = await login('viewer@example.test');
    const strangerHeaders = await login('stranger@example.test');
    const createdUser = await app.inject({ method: 'POST', url: '/v1/users', headers: adminHeaders, payload: { email: 'new@example.test', password } });
    assert.equal(createdUser.statusCode, 201, createdUser.body);
    assert.equal(createdUser.json().password_hash, undefined);
    const deniedUser = await app.inject({ method: 'POST', url: '/v1/users', headers: viewerHeaders, payload: { email: 'bad@example.test', password } });
    assert.equal(deniedUser.statusCode, 403);
    const disable = await app.inject({ method: 'PATCH', url: `/v1/users/${createdUser.json().id}`, headers: adminHeaders, payload: { active: false } });
    assert.equal(disable.statusCode, 200, disable.body);
    const disabledLogin = await app.inject({ method: 'POST', url: '/v1/auth/login', headers: { origin }, payload: { email: 'new@example.test', password } });
    assert.equal(disabledLogin.statusCode, 401);
    let response = await app.inject({ method: 'POST', url: '/v1/projects', headers: { ...adminHeaders, 'x-csrf-token': 'wrong' }, payload: { name: 'Team' } });
    assert.equal(response.statusCode, 403);
    response = await app.inject({ method: 'POST', url: '/v1/projects', headers: adminHeaders, payload: { name: 'Team' } });
    assert.equal(response.statusCode, 202, response.body);
    const project = response.json().id;
    assert.equal(response.json().state, 'pending');
    response = await app.inject({ method: 'PUT', url: `/v1/projects/${project}/members/${viewer}`, headers: adminHeaders, payload: { role: 'viewer' } });
    assert.equal(response.statusCode, 200, response.body);
    response = await app.inject({ method: 'GET', url: '/v1/projects', headers: viewerHeaders });
    assert.equal(response.json().items.length, 1);
    response = await app.inject({ method: 'GET', url: '/v1/projects', headers: strangerHeaders });
    assert.equal(response.json().items.length, 0);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/audit`, headers: strangerHeaders });
    assert.equal(response.statusCode, 404);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/operations`, headers: strangerHeaders });
    assert.equal(response.statusCode, 404);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/operations`, headers: viewerHeaders });
    assert.equal(response.statusCode, 200, response.body);
    assert.equal(response.json().items[0].kind, 'project.create');
    assert.equal(response.json().items[0].request, undefined);
    assert.equal(response.json().items[0].secret_payload, undefined);
    response = await app.inject({ method: 'PUT', url: `/v1/projects/${project}/members/${viewer}`, headers: viewerHeaders, payload: { role: 'admin' } });
    assert.equal(response.statusCode, 403);
    response = await app.inject({ method: 'PUT', url: `/v1/projects/${project}/members/${admin}`, headers: adminHeaders, payload: { role: 'viewer' } });
    assert.equal(response.statusCode, 409);
    response = await app.inject({ method: 'PATCH', url: `/v1/users/${admin}`, headers: adminHeaders, payload: { active: false } });
    assert.equal(response.statusCode, 409);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/audit`, headers: adminHeaders });
    assert.equal(response.statusCode, 200); assert.equal(response.json().items.length, 2);
    response = await app.inject({ method: 'DELETE', url: `/v1/projects/${project}/members/${admin}`, headers: adminHeaders });
    assert.equal(response.statusCode, 409, 'last project administrator cannot be removed');
    response = await app.inject({ method: 'POST', url: `/v1/projects/${project}/members`, headers: viewerHeaders, payload: {email:'stranger@example.test',role:'admin'} });
    assert.equal(response.statusCode, 403);
    response = await app.inject({ method: 'POST', url: `/v1/projects/${project}/instances/${randomUUID()}/credentials/rotate`, headers: viewerHeaders });
    assert.equal(response.statusCode, 403, 'viewers cannot rotate credentials');
    response=await app.inject({method:'POST',url:`/v1/projects/${project}/retry`,headers:viewerHeaders});assert.equal(response.statusCode,403,'viewers cannot retry project initialization');
    response = await app.inject({ method: 'POST', url: `/v1/projects/${project}/members`, headers: adminHeaders, payload: {email:'STRANGER@example.test',role:'maintainer'} });
    assert.equal(response.statusCode, 200, response.body);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/instances`, headers: strangerHeaders });
    assert.equal(response.statusCode, 200);
    response = await app.inject({ method: 'DELETE', url: `/v1/projects/${project}/members/${stranger}`, headers: adminHeaders });
    assert.equal(response.statusCode, 200);
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/instances`, headers: strangerHeaders });
    assert.equal(response.statusCode, 404, 'removal takes effect for existing sessions');
    response=await app.inject({url:`/v1/projects/${project}/instances/${randomUUID()}/statistics`,headers:strangerHeaders});assert.equal(response.statusCode,404,'statistics are project scoped');
    response = await app.inject({ method: 'GET', url: `/v1/projects/${project}/audit`, headers: adminHeaders });
    assert.ok(response.json().items.some((x:{action:string})=>x.action==='member.remove'));
    response = await app.inject({ method: 'POST', url: '/v1/auth/logout', headers: { ...viewerHeaders, origin: 'https://foreign.test' } });
    assert.equal(response.statusCode, 403);
    response = await app.inject({ method: 'POST', url: '/v1/auth/logout', headers: viewerHeaders });
    assert.equal(response.statusCode, 200);
    response = await app.inject({ method: 'GET', url: '/v1/auth/me', headers: viewerHeaders });
    assert.equal(response.statusCode, 401);
    const changingHeaders=await login('viewer@example.test');
    response=await app.inject({method:'POST',url:'/v1/auth/password',headers:changingHeaders,payload:{currentPassword:'wrong-password',password:'new-password-for-viewer'}});
    assert.equal(response.statusCode,403);
    response=await app.inject({method:'POST',url:`/v1/users/${stranger}/password`,headers:changingHeaders,payload:{password:'unauthorized-new-password'}});
    assert.equal(response.statusCode,403);
    response=await app.inject({method:'POST',url:'/v1/auth/password',headers:changingHeaders,payload:{currentPassword:password,password:'new-password-for-viewer'}});
    assert.equal(response.statusCode,200,response.body);
    response=await app.inject({url:'/v1/auth/me',headers:changingHeaders});assert.equal(response.statusCode,401);
    response=await app.inject({method:'POST',url:'/v1/auth/login',headers:{origin},payload:{email:'viewer@example.test',password}});assert.equal(response.statusCode,401);
    response=await app.inject({method:'POST',url:'/v1/auth/login',headers:{origin},payload:{email:'viewer@example.test',password:'new-password-for-viewer'}});assert.equal(response.statusCode,200,response.body);
    const changedSession={cookie:`expbuild_session=${response.cookies[0]!.value}`};
    response=await app.inject({method:'POST',url:`/v1/users/${viewer}/password`,headers:adminHeaders,payload:{password:'administrator-reset-password'}});assert.equal(response.statusCode,200,response.body);
    response=await app.inject({url:'/v1/auth/me',headers:changedSession});assert.equal(response.statusCode,401,'administrator reset revokes existing sessions');
    const passwordAudit=await pool.query("SELECT details FROM audit_events WHERE action IN ('auth.password.change','user.password.reset')");
    assert.equal(passwordAudit.rows.length,2);
    assert.equal(JSON.stringify(passwordAudit.rows).includes('password'),false,'passwords must not appear in audit details');
    // Membership is read on each request, not frozen in a session token.
    await pool.query('UPDATE users SET active=false WHERE id=$1', [admin]);
    response = await app.inject({ method: 'GET', url: '/v1/projects', headers: adminHeaders });
    assert.equal(response.statusCode, 401);
  } finally {
    await app.close(); await pool.end();
    await root.query(`DROP DATABASE "${database}"`); await root.end();
  }
});
